### ISSUE TITLE
Please delete the Wrap

### ISSUE THREAD

**Issue by stephanlachnit** [mesonbuild/vulkan-validationlayers#3]
Newer version can't be provided as a Wrap due to the folder structure (headers install with a `vulkan/` prefix, which is not present in the repo structure). A while back I asked to change the folder structure, with this reply: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2331#issuecomment-731376649

Since they aren't intended to be used by projects and the original repo that wanted to use this now has changed to a different solution, I think the Wrap should be deleted.

**Comment by jpakkane** [comment]
We won't delete old wraps. Doing so could break old projects that are still using them. Eventually we might want to add an option to hide them from the default view, but there aren't that many wraps yet so this is not an urgent issue.

**Comment by eli-schwartz** [comment]
We could use `configure_file(input: '../foo.h', output: 'foo.h', copy: true)` from a "vulkan/meson.build" to make this work.

**Comment by jpakkane** [comment]
Anyhow, this repo is no longer used, further discussion should go in the `wrapdb` repo so closing.
